---
title: "QML 2025 Final Reflection"
authors: "Sandria Tran Violet Manson"
date: 11-28-2025
format: pdf
---

|  |  |
|----------------------|--------------------------------------------------|
| Group Project title | Re-Analyzing Ota, Hartsuiker and Haywood (2009) |
| Group members | Violet Manson, Sandria Tran

## Summary 


## Methods


## Results 


## Final Reflection

-   (300 Words) There is no word limit, but we suggest to keep this to one page.
-   You should propose and justify a mark for yourself based on your experience with the course and with working on you Group Project. Note that your mark suggestion is just a suggestion and the tutors and I will make the final decision. You must follow the marking rubric of the course available at <https://uoelel.github.io/qml/assessments.html#feedback-and-marking>.

## Group Project (Links)
- Link to Violet's Comparative Analysis Paper - Github 
- Link to Workshop based on Model (Bayesian Hierarchical Logistic Regression)
- Link to our results 
- Link to our Code 
-   Include your Group Project output or a link to it here.
-   If the output requires an explanation, but the output itself resides somewhere else and you are including a link, you can add the explanation here (for example, this is helpful when you video/audio recorded your output and you need to describe what you have done).
-   If unsure how to include your output, post a question on Piazza.
